//user
const TYPES = {
  USER: {
    SET_AUTHENTICATED: 'SET_AUTHENTICATED',
    SET_UNAUTHENTICATED: 'SET_UNAUTHENTICATED',
    SET_USER: 'SET_USER',
    LOADING_USER: 'LOADING_USER',
    MARK_NOTIFICATIONS_READ: 'MARK_NOTIFICATIONS_READ',
  },
  UI: {
    SET_ERRORS: 'SET_ERRORS',
    LOADING_UI: 'LOADING_UI',
    CLEAR_ERRORS: 'CLEAR_ERRORS',
    LOADING_DATA: 'LOADING_DATA',
    STOP_LOADING_UI: 'STOP_LOADING_UI',
    EXPAND_SCREAM: 'EXPAND_SCREAM',
    CLOSE_SCREAM: 'CLOSE_SCREAM',
  },
  DATA: {
    SET_SCREAMS: 'SET_SCREAMS',
    SET_SCREAM: 'SET_SCREAM',
    LIKE_SCREAM: 'LIKE_SCREAM',
    UNLIKE_SCREAM: 'UNLIKE_SCREAM',
    DELETE_SCREAM: 'DELETE_SCREAM',
    POST_SCREAM: 'POST_SCREAM',
    SUBMIT_COMMENT: 'SUBMIT_COMMENT',
    SET_USER_DETAILS: 'SET_USER_DETAILS',
    SET_COMMENTS: 'SET_COMMENTS',
  },
};

export default TYPES;
